server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;

    # Vue SPA 대응 (중요)
    try_files $uri /index.html;
  }

  # json-server API 연결
  location /api/ {
    proxy_pass http://localhost:3000/;
  }
}